### PR TITLE
added main function

### PR DESCRIPTION
**Pull request by Tinggaard**
hello, pls sig at det her må komme ind i masteren

### CODE REVIEW

**Comment by Maxnm47** [comment]
this sucks

**Comment by Maxnm47** [comment]
kys

**Review by Maxnm47 — COMMENTED** [review]
not good

**Review by Armin1945 — APPROVED** [review]
approved

**Review by Thomast2001 — APPROVED** [review]
noice

**Review by Maxnm47 — APPROVED** [review]

**Review by MikkelBaekgaardJoergensen — APPROVED** [review]
nice

**Pull request merged**
